# Site settings
title: The Health-related Water Microbiology Lab
email: huiyun.wu@wsu.edu
descriptioin: > # this means to ignore newlines until "baseurl:"
   The website for the research group of Dr. Huiyun Wu at the Washington State University
   in the Department of Civil and Environmental Engineering 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wuhuiyun07.github.io/Wulab.github.io/" # the base hostname & protocol for your site
github_username: wuhuiyun07
logo: assets/img/HWu.jpg

# Build settings
markdown: kramdown

collections:
  members:
  output: ture
  science:
  output: true
  papers:
    output: true


plugins:
  - jekyll-sitemap